# Generated by Django 5.2.4 on 2025-08-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=4),
        ),
    ]
